# Generated by Django 3.2.4 on 2021-08-22 23:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dsp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('usp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ping', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bytes_sent', models.CharField(max_length=300, null=True)),
                ('bytes_recieve', models.CharField(max_length=300, null=True)),
                ('servid', models.SmallIntegerField(null=True)),
                ('testdata', models.DateTimeField(default=datetime.datetime(2021, 8, 23, 2, 40, 18, 304273))),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-testdata'],
            },
        ),
    ]
