# Generated by Django 3.2.4 on 2021-08-24 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0004_auto_20210823_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='testdata',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 13, 40, 19, 258129)),
        ),
    ]
