# Generated by Django 3.2.4 on 2021-08-24 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0005_alter_measurement_testdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='time',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='testdata',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 15, 46, 33, 154571)),
        ),
    ]
