# Generated by Django 3.2.4 on 2021-08-25 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0008_auto_20210825_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='enddata',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 19, 3, 23, 256970), null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='testdata',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 21, 3, 23, 256970)),
        ),
    ]
