# Generated by Django 3.2.4 on 2021-08-25 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0009_auto_20210825_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='enddata',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 6, 5, 29, 455293)),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='testdata',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 21, 5, 29, 455293)),
        ),
    ]
